global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:9191"]

  - job_name: "dcgm_exporter"
    static_configs:
      - targets: ["dcgm_exporter:9400"]
