global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["127.0.0.1:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["127.0.0.1:9191"]

  - job_name: "dcgm_exporter"
    static_configs:
      - targets: ["127.0.0.1:9400"]
